apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdg-vientiane-user
  namespace: gdg-vientiane-api
  labels:
    app: gdg-vientiane-user
spec:
  selector:
    matchLabels:
      app: gdg-vientiane-user
  template:
    metadata:
      labels:
        app: gdg-vientiane-user
    spec:
      containers:
      - name: gdg-vientiane-user-container
        image: 883347473856.dkr.ecr.ap-southeast-1.amazonaws.com/gdg-user-service:latest
        imagePullPolicy: Always
        ports:
            - containerPort: 7000
        resources:
          requests:
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  namespace: gdg-vientiane-api
  name: gdg-vientiane-user-service
  labels:
    app: gdg-vientiane-user
spec:
  type: NodePort
  selector:
    app: gdg-vientiane-user
  ports:
    - port: 80
      targetPort: 7000
      protocol: TCP

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gdg-vientiane-api
  name: gdg-vientiane-user
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gdg-vientiane-user
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50