apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gdg-eks
  region: ap-southeast-1

vpc:
  id: "vpc-8688b2e1"
  subnets:
    public:
      ap-southeast-1a:
          id: "subnet-81ff11e7"
      ap-southeast-1b:
          id: "subnet-dea0bf97"
      ap-southeast-1c:
          id: "subnet-a6d471ff"
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (default)

iam:
  withOIDC: true   
  serviceAccounts:
    - metadata:
        name: aws-load-balancer
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true  

managedNodeGroups:
  - name: gdg-eks-ng
    instanceType: t2.medium
    minSize: 2
    maxSize: 10
